### ISSUE TITLE
Use CCA Root Certificates as Trust Anchor

### ISSUE THREAD

**Issue by abrbhat** [iSPIRT/digital-sky-api#57]
https://github.com/iSPIRT/digital-sky-api/blob/f83c42b4d85daee1e6e3f9fd130dcbaca90f5d24/src/main/java/com/ispirit/digitalsky/service/DigitalCertificateValidatorServiceImpl.java#L53

Currently the trust anchors for validating the Manufacturer's Certificate Chain are the certificates within the chain itself. This renders the below line of code useless:
https://github.com/iSPIRT/digital-sky-api/blob/f83c42b4d85daee1e6e3f9fd130dcbaca90f5d24/src/main/java/com/ispirit/digitalsky/service/DigitalCertificateValidatorServiceImpl.java#L59

It also allows to Manufacturer to upload arbitrary certificate chains rendering the signature verification process insecure.

Certificate Chain verification should be done only against CCA Root Certificates as trust anchors.
http://www.cca.gov.in/cca/?q=root_certificate.html

@CharanSahaj @bugobliterator @sidd-shetty @sidhantgoel

**Comment by charan1994** [comment]
This has been fixed [here](https://github.com/iSPIRT/digital-sky-api/commit/84fdc1802aeac0c2adad1ca0574edac74766b381)
